wallpaper {
    monitor = DP-1
    path = ~/Downloads/13ol6fbk1in91.png
    # monitor = DP-2, ~/wallpapers/other.png # For multiple monitors
    # fit_mode = contain # Optional: contain, cover, etc.
}
